#!/usr/bin/env python3
"""
Build condor/v14_nevents.py -- the job-splitting cache for the v14 PFNano samples.

The v14 samples are private and NOT in DAS, so submit.py's split_func() cannot
query dasgoclient for them and would silently fall back to 20 files/job. This
writes a cache in the SAME {nevents, nfiles, evts_per_file} schema as
das_nevents.py, keyed by the dataset names from vbsvvh_v14.dataset_name(), so
submit.py just merges it into das_info and splitting works unchanged.

nevents is an ESTIMATE: a few files per sample are opened and their Events
entries averaged, then multiplied by the sample's file count. That is all
split_func needs -- it only uses evts_per_file to pick files-per-job.

Usage:  python3 make_v14_nevents.py <counts.json>
where counts.json is [[era, category, sname, nfiles, mean_entries_or_null], ...]
"""
import json
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)))
import vbsvvh_v14

DEFAULT_EVTS_PER_FILE = 20000  # only for samples whose probes all failed


def main():
    rows = json.load(open(sys.argv[1]))
    out, n_est, n_fallback = {}, 0, 0
    for era, category, sname, nfiles, mean in rows:
        name = vbsvvh_v14.dataset_name(era, category, sname)
        if mean:
            epf = int(round(mean))
            n_est += 1
        else:
            epf = DEFAULT_EVTS_PER_FILE
            n_fallback += 1
        out[name] = {"nevents": epf * nfiles, "nfiles": nfiles, "evts_per_file": epf}

    dest = os.path.join(os.path.dirname(os.path.realpath(__file__)), "v14_nevents.py")
    with open(dest, "w") as f:
        f.write("# Auto-generated by make_v14_nevents.py -- DO NOT EDIT BY HAND.\n")
        f.write("# Job-splitting cache for the v14 PFNano samples, which are private\n")
        f.write("# and therefore absent from DAS. Same schema as das_nevents.py.\n")
        f.write("# nevents/evts_per_file are ESTIMATES from sampling a few files per\n")
        f.write("# sample; they drive files-per-job only, never physics.\n")
        f.write(f"# {n_est} sampled, {n_fallback} fell back to {DEFAULT_EVTS_PER_FILE} evts/file.\n\n")
        f.write("v14_info = {\n")
        for k in sorted(out):
            v = out[k]
            f.write(f'    "{k}": {{"nevents": {v["nevents"]}, "nfiles": {v["nfiles"]}, "evts_per_file": {v["evts_per_file"]}}},\n')
        f.write("}\n")
    print(f"wrote {dest}: {len(out)} samples ({n_est} sampled, {n_fallback} fallback)")


if __name__ == "__main__":
    main()
